spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    general:
      kafka-topic: trader-updates

incentive-api-url: http://localhost:8080/incentive